ojss/urls.py
from django.contrib import admin
from django.urls import path
from ojss_app import views
from  django.contrib.auth.views import login

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.UserController.login, name='index'),
    path("search", views.UserController.show_home_page, name='search'),
    path("job_details/<int:job_id>",views.ApplicationController.job_details, name="job_details"),
    path("apply/<int:job_id>", views.ApplicationController.apply, name='apply'),
    path("see_applications", views.ApplicationController.my_applications, name="my_applications"),
    path("seeker_register",views.UserController.seekerRegister, name='seeker_register'),
    path("recruiter_register", views.UserController.recruiterRegister, name='recruiter_register'),
    path("^search?", views.SearchController.search_for_jobs, name="search_list"),
    path("seekerprofile",views.UserController.seekerProfile, name= 'seeker_profile'),
    path("recruiterprofile",views.UserController.recruiterProfile, name='recruiter_profile'),
    path("skills",views.UserController.add_skills, name='skills'),
    path("add_jobs", views.JobController.add_job, name='add_job'),
    path("manage_jobs", views.JobController.manage_jobs, name='manage_jobs'),
    path('job_edit/<int:job_id>', views.JobController.edit_job, name='job_edit'),
    path('applications/<int:application_id>',views.JobController.applications, name='applications'),
    path('applicant_details/<int:job_id>/<int:seeker_profile_id>',
         views.JobController.applicant_details, name='applicant_details'),
    path('accept_applicant/<int:application_id>',views.JobController.accept_applicant, name='accept_applicant'),
    path('reject_applicant/<int:application_id>',views.JobController.reject_applicant, name='reject_applicant'),
    path('logout', views.UserController.logout_user, name='logout'),
    path('ajax/load_subcategory',views.AjaxRequestController.subcategory, name='subcategory'),
    path('interview_call/<int:application_id>', views.JobController.interview_call, name='send_interview_call'),
    path('ajax/load_category', views.AjaxRequestController.category, name='category')
]

ojss_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager



class UserManager(BaseUserManager):

    def create_user(self,email,password=None,is_active=True,is_recruiter = False, is_seeker = False, is_staff=False, is_admin= False):

        if not email:
            raise ValueError("User must have a valid email address")

        if not password:
            raise ValueError("User must have a password")

        user_obj = self.model(

            email = self.normalize_email(email)
        )

        user_obj.set_password(password)

        user_obj.is_active = is_active

        user_obj.is_recruiter = is_recruiter

        user_obj.is_seeker = is_seeker

        user_obj.is_admin = is_admin

        user_obj.is_staff = is_staff

        user_obj.save(using=self._db)

        return  user_obj


    def create_staffuser(self,email,password):
        user = self.create_user(
            email,
            password,
            is_staff=True
        )
        return user


    def create_superuser(self,email,password=None):
        user = self.create_user(
            email,
            password,
            is_admin=True,
            is_staff=True
        )

        return user





class User(AbstractBaseUser):
    email = models.EmailField(

        verbose_name='Email Address',
        max_length=255,
        unique=True,
    )

    is_active = models.BooleanField(default=True)
    is_recruiter = models.BooleanField(default=False)
    is_seeker = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    register_Date = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []

    object = UserManager()

    def __str__(self):
        return  self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True



class SeekerProfile(models.Model):

    GENDER_CHOICES = (
        ('M','MALE'),
        ('F','FEMALE'),
    )

    seeker = models.OneToOneField(User,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    gender = models.CharField(max_length=1,
                              choices=GENDER_CHOICES,
                              default='M')
    address = models.CharField(max_length=255)
    phone = models.IntegerField(max_length=10)
    birthDate = models.DateField()
    current_job_role = models.CharField(max_length=255)
    current_company = models.CharField(max_length=255)



    def __str__(self):
        return self.first_name


class RecruiterProfile(models.Model):

    GENDER_CHOICES = (
        ('M', 'MALE'),
        ('F', 'FEMALE'),
    )

    recruiter = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    gender = models.CharField(max_length=1,
                              choices=GENDER_CHOICES,
                              default='M')
    company_name = models.CharField(max_length=255)
    company_address = models.CharField(max_length=255)
    company_phone = models.IntegerField()
    job_role = models.CharField(max_length=255)

    def __str__(self):
        return self.first_name


class Category(models.Model):

    category_name = models.CharField(max_length=255)


    def __str__(self):
        return self.category_name


class Subcategory(models.Model):

    sub_category_name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.sub_category_name






class Job(models.Model):
    job_role = models.CharField(max_length=255)
    job_description = models.CharField(max_length=1000)
    organization = models.CharField(max_length=255)
    remuneration = models.IntegerField()
    location = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL,null=True)
    sub_category = models.ForeignKey(Subcategory, on_delete=models.SET_NULL, null=True)
    skill_required_1 = models.CharField(max_length=255)
    skill_required_2 = models.CharField(max_length=255)
    skill_required_3 = models.CharField(max_length=255, blank=True, null=True)
    skill_required_4 = models.CharField(max_length=255, blank=True, null=True)
    skill_required_5 = models.CharField(max_length=255, blank=True, null=True)
    deadline = models.DateField()
    posted_date = models.DateField(auto_now_add=True)
    job_ad_flag = models.CharField(max_length=1)
    recruiter = models.ForeignKey(RecruiterProfile,on_delete=models.CASCADE)



    def __str__(self):
        return self.job_role



class SeekerSkillset(models.Model):

    seeker = models.OneToOneField(SeekerProfile,on_delete=models.CASCADE)
    skill_1 = models.CharField(max_length=255)
    skill_2 = models.CharField(max_length=255, blank=True, null=True)
    skill_3 = models.CharField(max_length=255, blank=True, null=True)
    skill_4 = models.CharField(max_length=255, blank=True, null=True)
    skill_5 = models.CharField(max_length=255, blank=True, null=True)


    def __str__(self):
        return self.seeker


class Application(models.Model):


    APPLICATION_CHOICES = (
        ('A', 'ACTIVE'),
        ('S', 'SELECTED'),
        ('R', 'REJECTED'),
        {'I', 'Interview'},
    )


    seeker = models.ForeignKey(SeekerProfile, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    seeker_name = models.CharField(max_length=255)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    cover_letter = models.CharField(max_length=1000)
    cv = models.CharField(max_length=1000)
    matching_score = models.IntegerField()
    status = models.CharField(max_length=1,
                              choices=APPLICATION_CHOICES,
                              default='M')



class Message(models.Model):



    message_type = models.CharField(max_length=1)
    seeker = models.ForeignKey(SeekerProfile, on_delete=models.CASCADE)
    recruiter = models.ForeignKey(RecruiterProfile,on_delete=models.CASCADE)
    application = models.ForeignKey(Application,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)


class Interview(models.Model):


    interview_date = models.DateTimeField(auto_now_add=True)
    application = models.ForeignKey(Application, on_delete=models.CASCADE)

ojss_app/forms.py
from  django import  forms
from  django.forms import ModelForm
from  django.contrib.auth.forms import  UserCreationForm
from  django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import User,SeekerProfile,RecruiterProfile,SeekerSkillset,Job,Category,Subcategory, Interview, Application



class SeekerRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True,max_length=255)


    class Meta:
        model = User
        fields = (
            'email',
            'password1',
            'password2'
        )


    def save(self, commit=True):
        user = super(UserCreationForm,self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.set_password(self.cleaned_data['password1'])
        user.is_seeker = True
        user.is_recruiter = False

        if commit:
            user.save()


        return  user


class RecruiterRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True,max_length=255)

    class Meta:
        model = User

        fields = (
            'email',
            'password1',
            'password2'

        )


    def save(self, commit=True):
        user = super(UserCreationForm,self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.set_password(self.cleaned_data['password1'])
        user.is_seeker = False
        user.is_recruiter = True

        if commit:
            user.save()

        return  user



class SeekerProfileForm(forms.Form):


    class Meta:
        model = SeekerProfile

    GENDER_CHOICES = [
        ('M', 'MALE'),
        ('F', 'FEMALE'),
    ]

    first_name = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class' : 'profile-form-style'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'profile-form-style'}))
    gender = forms.ChoiceField(label='Gender',choices=GENDER_CHOICES,widget=forms.TextInput(attrs={'class' : 'profile-form-style'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class' : 'profile-form-style'}))
    phone = forms.IntegerField(widget=forms.TextInput(attrs={'class' : 'profile-form-style'}))
    birthDate = forms.DateTimeField(widget=forms.TextInput(attrs={'class' : 'profile-form-style'}))
    current_job_role = forms.CharField(widget=forms.TextInput(attrs={'class' : 'profile-form-style'}))
    current_company = forms.CharField(widget=forms.TextInput(attrs={'class' : 'profile-form-style'}))



class RecruiterProfileForm(forms.Form):


    class Meta:
        model = RecruiterProfile

    GENDER_CHOICES = [
        ('M', 'MALE'),
        ('F', 'FEMALE'),
    ]

    first_name = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'profile-form-style'}))
    last_name = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'profile-form-style'}))
    gender = forms.ChoiceField(label='Gender', choices=GENDER_CHOICES,
                               widget=forms.TextInput(attrs={'class': 'profile-form-style'}))
    company_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'profile-form-style'}))
    company_address = forms.CharField(widget=forms.TextInput(attrs={'class': 'profile-form-style'}))
    company_phone = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'profile-form-style'}))
    job_role = forms.CharField(widget=forms.TextInput(attrs={'class': 'profile-form-style'}))



class SkillForm(forms.Form):

    class Meta:
        model = SeekerSkillset

    skill_1 = forms.CharField(max_length=255)
    skill_2 = forms.CharField(max_length=255, required=False)
    skill_3 = forms.CharField(max_length=255, required=False)
    skill_4 = forms.CharField(max_length=255, required=False)
    skill_5 = forms.CharField(max_length=255, required=False)



class CreateJobForm(forms.Form):


    AD_CHOICES = [
        ('Y', 'YES'),
        ('N', 'NO'),
    ]

    class Meta:
        model = Job

    job_role = forms.CharField(max_length=255)
    job_description = forms.CharField(max_length=255, widget=forms.Textarea)
    category = forms.ModelChoiceField(queryset=Category.objects.all())
    sub_category = forms.ModelChoiceField(queryset=Subcategory.objects.all())
    organization = forms.CharField(max_length=255)
    remuneration = forms.IntegerField()
    location = forms.CharField(max_length=255)
    skill_required_1 = forms.CharField(max_length=255)
    skill_required_2 = forms.CharField(max_length=255)
    skill_required_3 = forms.CharField(max_length=255, required=False)
    skill_required_4 = forms.CharField(max_length=255,required=False)
    skill_required_5 = forms.CharField(max_length=255, required=False)
    deadline = forms.DateField()
    job_ad_flag = forms.ChoiceField(label='ad_choices', choices=AD_CHOICES)



class InterviewForm(forms.Form):

    class Meta:
        model = Interview

    interview_Date = forms.DateField()
    interview_description = forms.CharField(max_length=1000)




class Application_form(forms.Form):

    class Meta:
        model = Application
        field = ('cv', 'cover_letter')


    cv = forms.CharField(max_length=1000, widget=forms.Textarea)
    cover_letter = forms.CharField(max_length=1000, widget=forms.Textarea)

ojss/templates/ojss_app/_job_item.html
<div class="container">

    {% if results %}

        {% for item in results %}

        <div class="job_list">


        <div class="row">
        <div class="col-md-12">

            <h2> {{ item.job_role }} </h2>

        </div>

    </div>
    <div class="row">
        <div class="col-md-12">

            <h4> Organization :{{ item.organization }}</h4>

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">


            <h6> Location : {{ item.location }}</h6>

        </div>

    </div>


    <div class="row">
        <div class="col-md-12">

             <h6> Renumeration : {{ item.remuneration }} </h6>

        </div>

    </div>

            <div class="row">
        <div class="col-md-12">

             <h6> Deadline : {{ item.deadline }} </h6>

        </div>

    </div>



        <div class="border-job"> </div>

    <div class="row">

        <div class="col-md-12">

            <p> {{ item.job_description|slice:":255"  }}</p>

        </div>


    </div>


        <a href="{% url 'job_details'   item.id  %}">

            <button class="btn bg-warning clearfix apply-button"  style="float: right"> Details </button>

        </a>


    </div>

    {% endfor %}

        {% else %}


         <div class="text-center page-center" style="border: none; width: auto">

                {% if messages %}

                      {% for message in messages %}


                         <h1 style="color: red; margin-top: 30px"> {{ message }}</h1>



                      {% endfor %}

                {%  endif %}

            </div>



    {% endif %}




    </div>

ojss/templates/ojss_app/appliedjobs.html
{%  extends "base.html" %}


{% block content %}


    <div class="container">


        <div class="text-center" style="margin-top: 40px">



            {% if applications %}

                <h2 > Applied Jobs </h2>

                <table class="table table-dark table-striped">
                      <thead>
                        <tr>
                             <th scope="col">#</th>
                             <th scope="col">Application Id</th>
                             <th scope="col">Your Score</th>
                             <th scope="col">Applied date</th>
                             <th scope="col">Status</th>
                        </tr>
                      </thead>
                        <tbody>


                        {%  for item in applications %}



                        {%  if item.status == 'A' %}
                        <tr style="background-color: #3ca861">
                        {% elif item.status == 'I' %}
                            <tr style="background-color: #1a82ae">
                            {% elif item.status == 'R' %}
                                <tr style="background-color: #d9534f">
                                {% else %}
                                    <tr style="background-color: #573e1c">
                                    {% endif %}


                          <th scope="row">{{ forloop.counter }}</th>
                             <td>{{ item.id }}</td>
                             <td>{{ item.matching_score }}</td>
                             <td>{{ item.date }}</td>
                             {% if item.status == 'R' %}
                                 <td> Application rejected </td>
                             {% elif item.status == "A" %}
                                 <td>Application sent</td>
                                 {% elif item.status == "I" %}
                                 <td>Selected for interview</td>
                                 {% else %}<td> Selected for next round</td>
                             {% endif %}

                        </tr>





                {% endfor %}


                </tbody>
                </table>

            {% else %}

                <h6 style="margin-top: 100px;color: #c9302c" > You have not applied for any jobs </h6>

             {% endif %}

        </div>


    </div>





{%  endblock %}

ojss/templates/ojss_app/createjob.html
{%  extends "base.html" %}

{% block content %}

    <div class="container">



              <div class="text-center">

                {% if messages %}

                      {% for message in messages %}

                         <p style="color: red; margin-top: 30px"> {{ message }}</p>

                      {% endfor %}

                {%  endif %}

            </div>


    <div class="text-center" id="jobform" data-subcategory-url="{% url 'subcategory'  %}" style="margin-top: 10px">

        {% if form %}
        <h2> CREATE NEW JOB </h2>
            {% else %}
            <a href="{% url 'add_job' %}">

                 <button class="btn btn-info" > Add Another Job </button>

            </a>
            <a href="{% url 'manage_jobs' %}" style="margin-left: 20px">

                <button class ="btn btn-warning" > View Created Job </button>

            </a>

        {% endif %}

    </div>


        <div class="form-group">




    <form method="post" id="profile-edit">

        {% csrf_token %}

    <div>

        {%  for  field in form %}
            <!--<label> {{ field.label }}</label>-->
            {% if field.label == 'ad_choices' %}

                <p style="margin-top: 30px;" >Advertise Job Now</p>



                <select name="job_ad_flag" style="display: block; margin-top: 10px;background-color: #1a1a1a; color: #3ca861">

                {% for key,value in form.fields.job_ad_flag.choices %}



                    <option class="option-values"
                            value="{{  key }}"{% if field.value == key %}selected {% endif  %}>{{ value }}</option>


                {% endfor %}


                </select>

                {% elif field.label == 'Category' %}

                    <label for="id_category" style="margin-top: 20px"> Job Category </label>
                    <select name="category" id="id_category" style="display: block; margin-top: 10px;background-color: #1a1a1a; color: #3ca861">

                    {% for key,value in form.fields.category.choices %}


                    <option class="option-values"
                            value="{{  key }}"{% if field.value == key %} selected {% endif  %}>{{ value }}</option>


                    {% endfor %}
                    </select>



                {% elif field.label == 'Sub category' %}

                    <label for="id_sub_category" style="margin-top: 20px"> Sub Category </label>
                    <select name="sub_category" id="id_sub_category" style="display: block; margin-top: 10px;background-color: #1a1a1a; color: #3ca861">

                    {% for key,value in form.fields.sub_category.choices %}


                    <option class="option-values"
                            value="-------------------"></option>


                    {% endfor %}
                    </select>



                {% elif field.label == "Deadline" %}


                <label for="{{ field.name }}" style="margin-top: 30px; margin-bottom: -40px">
                    {{ field.label }} </label>
                <input id="deadline" name="{{ field.name }}" class="form-control "
                       style="background-color: #1a1a1a; color: #ffffff">
                 </input>


                {%  elif field.label == "Job description" %}

                <label for="{{ field.name }}" style= "margin-top: 30px; margin-bottom: -40px">
                {{ field.label}}
                </label>
                <textarea name="{{ field.name }}" class="form-control" style="background-color: #1a1a1a; color: #ffffff">

                </textarea>


            {% else %}
                <label for="{{ field.name }}" style="margin-top: 30px; margin-bottom: -40px">
                    {{ field.label }} </label>
                <input  name="{{ field.name }}" class="form-control "
                       style="background-color: #1a1a1a; color: #ffffff">
                 </input>
            {% endif %}
            {{ field.errors }}
            {% endfor %}



    </div>


    {% if form %}

    <div class="create-job-button text-center" style="margin-top: 25px">


             <button type="submit" class="btn btn-success" style="width: 150px"> Create Job </button>
             <button type="reset" class="btn btn-danger" style="width: 150px"> Reset </button>


    </div>


    </form>

         </div>

    {% endif %}





    </div>













{%  endblock %}

ojss/templates/ojss_app/editjob.html
{%  extends "base.html" %}

{% block content %}


<div class="container">



              <div class="text-center">

                {% if messages %}

                      {% for message in messages %}

                         <h3 style="color: red; margin-top: 30px"> {{ message }}</h3>

                      {% endfor %}

                {%  endif %}

            </div>

    {%  if form %}

    <div class="text-center" style="margin-top: 20px">
        <h2> EDIT JOB </h2>
    </div>

    {% endif %}



    <div class="form-group" >




    <form method="post" id="jobform"  data-subcategory-url="{% url 'subcategory'  %}" >

        {% csrf_token %}

    <div>

        {%  for  field in form %}
            <!--<label> {{ field.label }}</label>-->
            {% if field.label == 'ad_choices' %}

                <p style="margin-top: 30px;" >Advertise Job Now</p>
                <select name="job_ad_flag" style="display: block; margin-top: 10px;background-color: #1a1a1a; color: #3ca861">

                {% for key,value in form.fields.job_ad_flag.choices %}



                    <option class="option-values"
                            value="{{  key }}"{% if field.value == key %}selected {% endif  %}>{{ value }}</option>


                {% endfor %}

                </select>


                {% elif field.label == "Deadline" %}


                <label for="{{ field.name }}" style="margin-top: 30px; margin-bottom: -40px">
                    {{ field.label }} </label>
                <input id="deadline" name="{{ field.name }}" class="form-control "
                       style="background-color: #1a1a1a; color: #ffffff"
                value="{{field.value.year}}-{{field.value.month}}-{{field.value.day}}">
                 </input>


                {%  elif field.label == "Job description" %}

                <label for="{{ field.name }}" style= "margin-top: 30px; margin-bottom: -40px">
                {{ field.label}}
                </label>
                <textarea name="{{ field.name }}" class="form-control"
                           style="background-color: #1a1a1a;
                           color: #ffffff">{{field.value}}</textarea>


                 </select>

                {% elif field.label == 'Category' %}

                    <label for="id_category" style="margin-top: 20px"> Job Category </label>
                    <select name="category" id="id_category" style="display: block; margin-top: 10px;background-color: #1a1a1a; color: #3ca861">

                    {% for key,value in form.fields.category.choices %}


                    <option class="option-values"
                            value="{{  key }}"{% if field.value == key %} selected {% endif  %}>{{ value }}</option>


                    {% endfor %}

                    </select>



                {% elif field.label == 'Sub category' %}


                    <label for="id_sub_category" style="margin-top: 20px"> Sub Category </label>
                    <select name="sub_category" id="id_sub_category" style="display:
                     block; margin-top: 10px;background-color: #1a1a1a; color: #3ca861">



                    <option class="option-values"
                            value="">{{ field.value }}</option>

                    </select>



            {% else %}
                <label for="{{ field.name }}" style="margin-top: 30px; margin-bottom: -40px">
                    {{ field.label }} </label>
                <input  name="{{ field.name }}" class="form-control "
                        value="{% if field.value %} {{field.value}}{% endif %}"
                       style="background-color: #1a1a1a; color: #ffffff">
                 </input>
            {% endif %}
            {{ field.errors }}
            {% endfor %}



    </div>


    {% if form %}


    <div class="create-job-button text-center" style="margin-top: 25px">


             <button type="submit" class="btn btn-success" style="width: 150px"> Save Job </button>
             <button type="reset" class="btn btn-danger" style="width: 150px"> Cancel </button>


    </div>

    {% endif %}


    </form>

         </div>

    </div>



{% endblock %}

ojss/templates/ojss_app/form.html
{% extends "base.html" %}

{%  block content %}

    <div class="container form-group">

    <div class="row">

        <div class="col-lg-6">
        <h2> ADD A NEW ENTRY </h2>
        </div>

    <div class="col-lg-6">
        <a href="{% url 'index' %}"> <button class="btn btn-dark"> Go back </button> </a>
    </div>

    </div>



    <form method="POST">
        {% csrf_token %}

        {%  for  field in form %}
            <label> {{ field.label }}</label>
            <input placeholder="{{ field.label }}" name="{{ field.name }}" class="form-control">
            {{ field.errors }}

        {% endfor %}

        <button type="submit" class="btn btn-success"> Submit </button>
    </form>



    </div>


{% endblock content %}

ojss/templates/ojss_app/index.html
{%  extends "base.html" %}

{% block content %}


    {%  if request.user.is_seeker %}



       {% include 'ojss_app/_job_item.html' %}


    {% else %}


                {% if messages %}

                      {% for message in messages %}

                          {% if message.tags == 'success' %}
                          <div class="text-center" id="messages">
                          <p style="color:#0d0d0d; height: 30px; font-size: 15px"   > {{ message }}</p>
                          </div>
                           {% endif %}
                      {% endfor %}

                {%  endif %}


        <div style="margin-top: 20px">

              {% include 'ojss_app/_job_item.html' %}

        </div>




    {% endif %}




{%  endblock content %}

ojss/templates/ojss_app/interview.html
{%  extends "base.html" %}

{% block content %}

<div class="text-center" id="interview-form" style="display: none">


        {% if not status %}

            <div class="interview-form" style="margin-top: 10px">



                     <form method="post" >

                     {%  csrf_token %}

            <div class="text-center"> <h2> Interview Form </h2></div>

                <div class="row">

            {% for field in form %}

                {% if field.label == 'Interview date' %}

                    <div class="col-md-4">

                     <label for="{{ field.name }}">{{field.label}}</label>
                      <input  name="{{ field.name }}" id="interview-date" class="form-control input-control"
                       style="background-color: #1a1a1a; color: #ffffff">
                       </input>

                     </div>
                {% else %}

                    <div class="col-md-8">

                     <label for="{{ field.name }}">{{field.label}}</label>
                      <textarea  name="{{ field.name }}" class="form-control input-control"
                       style="background-color: #1a1a1a; color: #ffffff">
                      </textarea>
                    </div>

                {% endif %}


            {% endfor %}

                </div>

                <a href="{% url 'send_interview_call' %}">
                    <button class="btn btn-info" style="margin-top: 20px"> SEND INTERVIEW CALL </button>
                </a>


        </form>

            </div>


        {% else %}

            <div class="text-center"> <h2> You have already sent interview invite  </h2></div>

            <div class="row">

            {% for field in form %}

                {% if field.label == 'Interview date' %}

                    <div class="col-md-4">

                     <label for="{{ field.name }}">{{field.label}}</label>
                      <input  name="{{ field.name }}" id="interview-date" class="form-control input-control"
                       style="background-color: #1a1a1a; color: #ffffff">
                       </input>

                     </div>
                {% else %}

                    <div class="col-md-8">

                     <label for="{{ field.name }}">{{field.label}}</label>
                      <textarea  name="{{ field.name }}" class="form-control input-control"
                       style="background-color: #1a1a1a; color: #ffffff">
                      </textarea>
                    </div>

                {% endif %}


            {% endfor %}

                </div>

        {% endif %}

    </div>


{% endblock %}

ojss/templates/ojss_app/subcategory_drop_down.html
{% for item in sub_category %}
<option value="{{ item.pk }}">{{ item.sub_category_name }}</option>
{% endfor %}